name       : mimalloc
version    : 1.7.6
release    : 1
source     :
    - https://github.com/microsoft/mimalloc/archive/refs/tags/v1.7.6.tar.gz : d74f86ada2329016068bc5a243268f1f555edd620b6a7d6ce89295e7d6cf18da
license    : MIT
component  : programming.library
summary    : A compact general purpose allocator with excellent performance.
description: |
    mimalloc (pronounced "me-malloc") is a general purpose allocator with excellent performance characteristics. It is a drop-in replacement for malloc and can be used in other programs without code changes.
setup      : |
    %cmake_ninja -DMI_BUILD_STATIC=OFF \
                 -DMI_BUILD_OBJECT=OFF \
                 -DMI_BUILD_TESTS=OFF \
                 -DMI_INSTALL_TOPLEVEL=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
